baseURL = "https://patchxr.com"
disableLanguages = []
paginate = "6"
summaryLength = "10"
theme = "patchxr-hugo"
title = "PatchXR"
[Languages.en]
contentDir = "content/"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[[menu.footer]]
URL = "faq"
name = "FAQ"
weight = 6
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 5
[[menu.footer]]
URL = "info"
name = "Info"
weight = 1
[[menu.footer]]
URL = "privacy-policy"
name = "Privacy"
weight = 4
[[menu.footer]]
URL = "blog"
name = "Blog"
weight = 3

[[menu.main]]
URL = "community"
name = "community"
weight = 2
[[menu.main]]
URL = "about"
name = "about"
weight = 3
[[menu.main]]
URL = "works"
name = "works"
weight = 4
[[menu.main]]
URL = "blog"
name = "blog"
weight = 5
[[menu.main]]
URL = "contact"
name = "contact"
weight = 6

[params]
address = "Physical Address?"
author = "PatchXR"
contact_form_action = "#"
description = "Patch is a native VR authoring tool that lets you build brand new digital instruments and play electronic music in a 3D space like never before."
email = "info@patchxr.com"
google_analytics_id = "UA-171710509-1"
home = "Home"
logo = "images/logo.png"
logo_1 = "images/logo-1.png"
logo_2 = "images/logo-2.png"
logotype = "images/patchXR-SOUNDmetaverse-grey.svg"
logo_light = "images/logo-alt.png"
mobile = "+555555555"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.carousel.min.css"
[[params.plugins.css]]
link = "plugins/aos/aos.css"
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/owl-carousel/owl.carousel.min.js"
[[params.plugins.js]]
link = "plugins/aos/aos.js"
[[params.plugins.js]]
link = "plugins/jquery.bootstrap-autohidingnavbar.js"
[[params.plugins.js]]
link = "plugins/highlight.js"
[params.preloader]
enable = false
preloader = "/images/logo-1.png"
[[params.social]]
URL = "https://www.facebook.com/patch.xr/"
icon = "tf-ion-social-facebook"
[[params.social]]
URL = "https://twitter.com/patch_xr"
icon = "tf-ion-social-twitter"
[[params.social]]
URL = "https://www.instagram.com/patch.xr/"
icon = "tf-ion-social-instagram"
[[params.social]]
URL = "https://www.youtube.com/channel/UCk_Ekjvy67qnNo-iM4-F_bA"
icon = "tf-ion-social-youtube"
[[params.social]]
URL = "https://www.linkedin.com/company/patch-xr/"
icon = "tf-ion-social-linkedin"
[[params.social]]
URL = "https://www.twitch.tv/patchxr"
icon = "tf-ion-social-twitch"
