---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: document
  path: data/en/homepage.yml
  label: Homepage
- type: directory
  path: content/blog
  label: Blog
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - blog-post
- type: directory
  path: content/community
  label: Community
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - patch-post
- type: document
  path: data/en/community.yml
  label: Community Info
  match: "**/*"
- type: document
  path: content/works/_index.md
  label: Works
- type: document
  path: data/en/patchathon.yml
  label: Patchathon
- type: document
  path: data/en/about.yml
  label: Info
- type: document
  path: content/info/_index.md
  label: Works/Info
- type: document
  path: data/en/team.yml
  label: Team
- type: directory
  path: content/jobs
  label: Jobs
  create: documents
  match: "**/*"
- type: document
  path: data/en/faq.yml
  label: FAQ
- type: document
  path: i18n/en.yaml
  label: i18n Strings
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.75.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.75.1
