# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions


name: Node.js CI

on: [push]

jobs:
  deploy:
    name: "Deploy to Linode"
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.119.0'
          # extended: true

      - name : npm ci 
        run: npm ci

      - name: Check Hugo Version
        run: hugo version

      - name: Build TinaCMS and the site
        run: npm run tinacms build && hugo

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/linode.key
          chmod 600 ~/.ssh/linode.key
          cat >>~/.ssh/config <<END
          Host linode
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/linode.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Deploy to Linode
        run: ssh linode 'cd /apps/patchXR_web_frontend/ && git pull && hugo -d public'

