# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]

jobs:
  deploy:
    name: "Deploy to Linode"
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/linode.key
          chmod 600 ~/.ssh/linode.key
          cat >>~/.ssh/config <<END
          Host linode
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/linode.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Check out the source
        run: whoami
        #run: ssh linode 'cd /apps/patch-api-server-dev && git fetch && git reset --hard origin/dev'
