on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.cluster021.hosting.ovh.net
        local-dir: /public/
        server-dir: /patchxr/2021/
        username: hanahanaki
        password: ${{ secrets.ftp_password }}